// src/services/github/pr.service.js
// Creates GitHub Pull Requests for AI-generated fixes
// CRITICAL: PRs are always created as DRAFTS — SoumyaOps NEVER auto-merges

import { Octokit } from '@octokit/rest';
import { retryWithBackoff } from '../../utils/retry.js';
import logger from '../../utils/logger.js';

/**
 * Create a draft PR with the AI-suggested fix
 *
 * @param {object} params
 * @param {string} params.githubToken
 * @param {string} params.owner
 * @param {string} params.repo
 * @param {string} params.baseBranch       - Branch to PR into (e.g. 'main')
 * @param {string} params.errorDescription - Short error summary for branch name / PR title
 * @param {string} params.fixExplanation   - Full explanation of the fix
 * @param {string} params.rootCause        - Root cause analysis
 * @param {Array}  params.filesChanged     - [{ path, after, description }]
 * @param {Array}  params.sourcesUsed      - RAG sources that informed the fix
 * @param {string} params.preventionTip    - Optional prevention advice
 * @returns {{ prUrl, prNumber, branch }}
 */
export async function createFixPR({
  githubToken,
  owner,
  repo,
  baseBranch = 'main',
  errorDescription,
  fixExplanation,
  rootCause,
  filesChanged = [],
  sourcesUsed = [],
  preventionTip,
}) {
  const octokit = new Octokit({ auth: githubToken });

  // Sanitize branch name
  const safeName = errorDescription
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 40);
  const branchName = `soumyaops/fix/${safeName}-${Date.now().toString(36)}`;

  // ── Step 1: Get base SHA ───────────────────────────────────────────────────
  const { data: refData } = await retryWithBackoff(() =>
    octokit.git.getRef({ owner, repo, ref: `heads/${baseBranch}` }),
  );
  const baseSha = refData.object.sha;

  // ── Step 2: Create branch ──────────────────────────────────────────────────
  await retryWithBackoff(() =>
    octokit.git.createRef({
      owner, repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    }),
  );
  logger.info(`[pr-service] Branch created: ${branchName}`);

  // ── Step 3: Commit each changed file ──────────────────────────────────────
  for (const file of filesChanged) {
    if (!file.path || !file.after) continue;

    // Get existing file SHA (required for updates, not for new files)
    let existingSha;
    try {
      const { data: existing } = await octokit.repos.getContent({
        owner, repo, path: file.path, ref: branchName,
      });
      existingSha = existing.sha;
    } catch { /* new file — no sha needed */ }

    await retryWithBackoff(() =>
      octokit.repos.createOrUpdateFileContents({
        owner, repo,
        path: file.path,
        message: `fix(soumyaops): ${file.description || errorDescription.slice(0, 60)}`,
        content: Buffer.from(file.after, 'utf-8').toString('base64'),
        branch: branchName,
        sha: existingSha,
      }),
    );

    logger.info(`[pr-service] Committed: ${file.path}`);
  }

  // ── Step 4: Build PR body ──────────────────────────────────────────────────
  const sourcesSection = sourcesUsed?.length
    ? `\n## 📚 Knowledge Sources Used\n\n${sourcesUsed.map((s, i) =>
        `**[${i + 1}] ${capitalise(s.source)}**${s.fileName ? ` · \`${s.fileName}\`` : ''}\n> ${s.excerpt?.slice(0, 150)}...`
      ).join('\n\n')}`
    : '';

  const filesSection = filesChanged?.length
    ? `\n## 📝 Files Modified\n\n${filesChanged.map(f =>
        `- \`${f.path}\`${f.description ? ` — ${f.description}` : ''}`
      ).join('\n')}`
    : '';

  const preventionSection = preventionTip
    ? `\n## 💡 Prevention Tip\n\n${preventionTip}`
    : '';

  const prBody = `## 🤖 SoumyaOps Auto-Fix Suggestion

> ⚠️ **This PR was created automatically by SoumyaOps AI.**
> **Please carefully review ALL changes before merging.**
> This PR is a draft and will NOT be merged automatically.

---

## 🐛 Root Cause

${rootCause || errorDescription}

## 🔧 Fix Explanation

${fixExplanation}
${filesSection}
${sourcesSection}
${preventionSection}

---

<details>
<summary>About SoumyaOps</summary>

This PR was generated by [SoumyaOps](https://github.com/soumyaops) using:
- RAG retrieval from your team's knowledge base
- Claude AI for fix generation
- Automated PR creation (never auto-merge)

Always treat AI-generated code as a starting point, not a final answer.
</details>`;

  // ── Step 5: Create draft PR ────────────────────────────────────────────────
  const { data: pr } = await retryWithBackoff(() =>
    octokit.pulls.create({
      owner, repo,
      title: `[SoumyaOps Fix] ${errorDescription.slice(0, 65)}`,
      head: branchName,
      base: baseBranch,
      body: prBody,
      draft: true, // ← ALWAYS draft
    }),
  );

  logger.info(`[pr-service] PR #${pr.number} created (draft): ${pr.html_url}`);

  return {
    prUrl: pr.html_url,
    prNumber: pr.number,
    branch: branchName,
  };
}

function capitalise(str) {
  return str ? str.charAt(0).toUpperCase() + str.slice(1) : '';
}